name: shoppy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # state management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  # A code generator for immutable classes
  freezed_annotation: ^2.4.4
  # A code generator for JSON serialization
  json_annotation: ^4.9.0
  # Flutter plugin for reading and writing simple key-value pairs for cache
  shared_preferences: ^2.5.3
  # For caching secured data
  flutter_secure_storage: ^9.2.4
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3
  # Provides Awesome UI components for Flutter
  shadcn_ui: ^0.27.0
  # Beautiful animations
  animate_do: ^4.2.0
  # To load and cache network images
  cached_network_image: ^3.4.1
  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  # Flutter plugin for selecting images from the Android and iOS image library
  image_picker: ^1.1.2
  # Effectively reduce the size of the transmission
  flutter_image_compress: ^2.4.0
  # Prints beautiful logs
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.14
  # code generator for riverpod
  riverpod_generator: ^2.6.0
  # Custom Lint rules are a powerful way to improve the maintainability of a project
  custom_lint: ^0.7.0
  # A developer tool for users of Riverpod, designed to help stop common issues and simplify repetitive tasks.
  riverpod_lint: ^2.6.1
  # A code generator for immutable classes
  freezed: ^2.5.7
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.9.0
  # Code generator for Retrofit
  retrofit_generator: ^9.2.0
  # Generates a native splash screen for Flutter
  flutter_native_splash: ^2.4.6
  # Changes the name of the app
  rename_app: ^1.6.5
  # Updates the app icon
  icons_launcher: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/utils/
  filename: assets.dart
  field_prefix: null